describe("Test example", function()
  it("Test can access vim namespace", function()
    assert.are.same(vim.trim("  a "), "a")
  end)
  it("Test can access plenary.nvim dependency", function()
    assert(require("plenary"), "Could not access plenary")
  end)
  it("Test can access module in lua/testproject", function()
    assert(require("testproject"), "Could not access main module")
  end)
  -- it("Test failure", function()
  --   assert.same(1, 2)
  -- end)
end)
